### ISSUE TITLE
How to parse output from MASTER?

### ISSUE THREAD

**Issue by sdwfrost** [blab/baltic#6]
Hi @evogytis 

I'm trying to parse the following NEXUS file produced by MASTER, which reads in fine with FigTree.

```
#nexus

Begin trees;
tree TREE = ((2[&type="L",location="1",time=0.0]:0.23551593012315475,1[&type="L",location="1",time=0.0]:0.23551593012315475)[&type="L",location="1",reaction="Coalescence",time=0.23551593012315475]:2.506442820016658,(3[&type="L",location="0",time=0.0]:0.2966241462553607,4[&type="L",location="0",time=0.0]:0.2966241462553607)[&type="L",location="0",reaction="Coalescence",time=0.2966241462553607]:2.445334603884452)[&type="L",location="1",reaction="Coalescence",time=2.741958750139813]:0.0;
End;
```

Any tips on how I can read this in using BALTIC, given that there are no tip dates etc.

**Comment by evogytis** [comment]
Hi Simon,

if you're trying to use `.loadNexus()` you can customise the import options like this:
```
ll=bt.loadNexus('/Users/evogytis/Documents/BLAB_baltic/sfrost.nex',absoluteTime=False,treestring_regex='tree TREE')
ll.treeStats()
```
If there's more things unique to the MASTER nexus format you could also write a minimal parser that could use baltic's tree string parsing machinery:

```
ll=bt.tree()
bt.make_tree(<tree string>,ll)
```

Let me know if that helps and if you discover any nexus examples that won't load.

**Comment by evogytis** [comment]
@sdwfrost Did it work?
