### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by phiweger** [blab/baltic#7]
This is a really nice and useful codebase, but it takes work to get through it. I guess it would need only a couple of changes to turn this into a library and make it work for Python 3.x -- are there any plans to do that? (This issue is more of an encouragement, as the lib would be very useful I think :)

**Comment by evogytis** [comment]
There is a branch of baltic attempting to do just that: https://github.com/Don86/baltic
As I don't use Python 3 myself I wouldn't know where to start, except for the obvious replacement of `print` calls with `sys.stderr.write()` or `sys.stdout.write()` depending on situation. I wouldn't be surprised if those are the only bits of baltic that are incompatible with Py3.

**Comment by phiweger** [comment]
Thanks, I'll have a look at that. Yeah, probably some class syntax is different as well, but generally I have found py3 not too be too different. Anyway, nice code :)
